<form action="/login" method="post" class="pure-form is-center">
    <fieldset>
    <?= $error == true ? "<legend>Failed Login</legend>" : "" ?>
        <input type="email" name="username" placeholder="Email" />
        <input type="password" name="password" placeholder="Password" />
        <label for="default-remember">
            <input type="checkbox" name="remember" id="default-remember" /> Remember me
        </label>
        <br>
        <button type="submit" class="pure-button pure-button-primary">Sign in</button>
    </fieldset>
</form>